Voxelum/x-minecraft-launcher

build/electron-publisher-custom.js, package.json
=> chore: fix the pub on azure

src/renderer/windows/main/pages/UserPageUserServiceStepper.vue
=> fix: make adding user service scrollable

xmcl-electron-app/build/electron-builder.config.ts, xmcl-electron-app/main/Controller.ts, xmcl-electron-app/main/ElectronLauncherApp.ts, xmcl-electron-app/plugins/esbuild.static.plugin.ts, xmcl-runtime/lib/app/Host.ts, xmcl-runtime/lib/app/LauncherApp.ts, xmcl-runtime/lib/app/LauncherAppManager.ts, xmcl-runtime/lib/app/win32/index.ts, xmcl-runtime/lib/managers/CredentialManager.ts
Fix #170.
Fix #171.
The root cause is the electron doesn't set the protocol correctly on linux.
Manually set the protocol as a workaround.
Tested on my wsl2 ubuntu 20.04.
=> Try to fix login issue on linux

CONTRIBUTING.zh.md, README.zh.md
;D 这是我在此项目的第一次贡献，希望以后能更多的参与到代码的贡献中。
有任何问题，欢迎随时指出，我将尽快修改。
=> docs: 修正了README.zh.md内的中文翻译并增加了贡献方式的中文译文

pnpm-lock.yaml, xmcl-keystone-ui/.eslintrc.json, xmcl-keystone-ui/src/hooks/useBackground.ts, xmcl-keystone-ui/src/windows/main/components/Background.vue, xmcl-keystone-ui/src/windows/main/components/Notifier.vue, xmcl-keystone-ui/src/windows/main/locales/en.yaml, xmcl-keystone-ui/src/windows/main/locales/zh-CN.yaml, xmcl-keystone-ui/src/windows/main/pages/modrinth/components/Categories.vue, xmcl-keystone-ui/src/windows/main/pages/setting/index.vue, xmcl-keystone-ui/src/windows/setup/SetDataRoot.vue, xmcl-keystone-ui/src/windows/setup/SetLocale.vue, xmcl-runtime-api/src/util/modCompatible.ts
pls we can now play music in this launcher
=> feat: added background video selection

README.md
I couldn't spot anything else. Also, what do you mean by "[...]modpacks with compliance[...]"?
=> Fix typos and whatnot in README

xmcl-electron-app/main/locales/es-ES.yaml
Translation of electron app to Spanish Spain
=> Translation to Spanish - Spain

xmcl-keystone-ui/src/windows/main/locales/zh-CN.yaml
=> update zh_CN translation

xmcl-keystone-ui/src/windows/main/locales/en.yaml, xmcl-keystone-ui/src/windows/main/locales/ru.yaml, xmcl-keystone-ui/src/windows/main/locales/zh-CN.yaml, xmcl-keystone-ui/src/windows/main/views/Modpack.vue
Correct ru tags translation and some zh translations.
Add a button that jump to Modriinth page.
=> Correct some translations & Add mrpack button

CONTRIBUTING.md, CONTRIBUTING.zh.md, xmcl-electron-app/.gitignore, xmcl-electron-app/build.ts, xmcl-electron-app/dist/.gitkeep
Fix no dist folder bug; Update contributing doc
=> Fix no dist folder bug; Update contributing doc

xmcl-electron-app/build.ts, xmcl-electron-app/dev.ts, xmcl-keystone-ui/src/composables/windowStyle.ts, xmcl-keystone-ui/src/views/AppSystemBar.vue, xmcl-keystone-ui/src/views/CurseforgeCard.vue
Bugfix: 
* re-fix the no dist folder when start debugging
* back button and traffic lights button overlap on macOS
* forge card layout
=> Bugfix: back button on macOS; forge card layout

assets/locales.json, xmcl-electron-app/main/locales/fr.yaml, xmcl-keystone-ui/locales/fr.yaml
And "French" to "Français" in `assets/locales.json`
=> Update FR locales

xmcl-keystone-ui/locales/en.yaml, xmcl-keystone-ui/locales/ru.yaml
Has some flaws due to differences in the declension of tenses.
=> :globe_with_meridians: Full Russian localisation

assets/locales.json, xmcl-keystone-ui/locales/it-IT.txt
this pulll request contain support italian lenguage
=> Italian language support

xmcl-keystone-ui/locales/en.yaml, xmcl-keystone-ui/src/views/ResourcePackActions.vue, xmcl-keystone-ui/src/views/ResourcePackItem.vue
1. Added correct tooltip to "show resource packs directory" button
2. Added option in context menu of resource pack to show it in folder
3. `save` -> `saves`
=> Small updates for resource pack

xmcl-keystone-ui/locales/ru.yaml
So, as I promised in #673, here's the completely rewritten from scratch translation into Russian. This translation is more original, correct and polite towards the end user.
Unlike #673, where I mostly translated English lines into Russian, in this translation I translated the lines according to what they do and what they are needed for (that is, I tried to adapt the translation).
Because of this, some lines may have a different meaning, but this meaning will better describe what a particular function does.
Here is some changes:
+ Letter `ё`
In some words, the letter `ё` was replaced with `е`. I tried to correct it in every possible word.
+ Tags in noun form
All tags have been converted to noun form for convenience and beauty.
+ Formatting
Formatting has changed a bit. This had no effect …
=> Update Russian translation #2

xmcl-keystone-ui/locales/en.yaml
I've looked through the translations for English, and I have noticed some grammar and spelling errors. I have forked this repository and corrected as many as I could find. I hope you will consider adding these!
=> Update english translation

pnpm-lock.yaml, xmcl-keystone-ui/package.json, xmcl-keystone-ui/src/components/InstanceManifestFileItem.vue, xmcl-keystone-ui/src/components/InstanceManifestFileTree.vue, xmcl-keystone-ui/src/components/StepConfig.vue, xmcl-keystone-ui/src/composables/instanceFileNodeData.ts, xmcl-keystone-ui/src/composables/instanceTemplates.ts, xmcl-keystone-ui/src/util/tree.ts, xmcl-keystone-ui/src/views/AppExportDialog.vue, xmcl-keystone-ui/src/views/AppShareInstanceDialog.vue, xmcl-keystone-ui/src/views/HomeInstanceInstallDialog.vue, xmcl-runtime/instance/InstanceServerInfoService.ts, xmcl-runtime/instanceIO/InstanceFileDiscover.ts, xmcl-runtime/instanceIO/InstanceManifestService.ts, xmcl-runtime/resource/ResourceManager.ts
- More compact UI
- Virtual scrolling of file tree by utilizing [@tanstack/virtual](https://github.com/TanStack/virtual): this reduces lag if there's massive amounts of files
- Added some utilities to flatten a tree
=> feat: virtualized file list for instance update dialog

.github/workflows/build.yml
Instead of constantly using AUR and updating through it, I changed build.yml and added ArchLinux support with .pacman output format, in the future it will be possible to update the launcher through it (just like with .deb, .rpm)
But what about AUR?
I will continue to update it
=> ArchLinux support

assets/locales.json, xmcl-electron-app/main/locales/pt-BR.yaml, xmcl-keystone-ui/locales/pt-BR.yaml
This pull request introduces a new translation for the project, with the goal of enhancing support for Brazilian users. The translation ensures that all key terms and phrases are accurately conveyed in Portuguese, while also improving the clarity of certain elements. This update aims to make the project more accessible and user-friendly for Portuguese-speaking players.
Thank you for considering this addition!
=> Translation Update for Portuguese (Brazil)

xmcl-runtime/java/JavaService.ts, xmcl-runtime/java/javaPaths.ts
As a java programmer, I mostly use sdkman for java, I think that those who also program and use sdkman will find this patch useful
=> Support for sdkman for Linux

docs/README.de.md
Changed the wording to better appeal to the German language, similar to my changes to the contribution guidelines translation.
=> docs: Better wording

xmcl-keystone-ui/locales/uk.yaml, xmcl-keystone-ui/src/views/HomeActions.vue, xmcl-keystone-ui/src/views/HomeLogDialog.vue, xmcl-keystone-ui/src/views/Me.vue
Added support for full collapse and expansion of news. Also, full localization into Ukrainian
https://github.com/user-attachments/assets/555b7fc9-9974-4d82-8c4f-017e9dc94e03
=> Redesign of the News menu in My Stuff

assets/locales.json, xmcl-electron-app/main/locales/ko.yaml, xmcl-keystone-ui/locales/ko.yaml
Added a Korean translation(Tested)
Discord : 0o00oo0o (그루프)
=> Added a Korean translation
